# Site settings
title: White Ravens Home
description: Baza główna White Ravens
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://whiteravens.net" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mauricio Urraco
user_description: I'm a Software Engineer from Argentina, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in world of Giving Circles working with Grapevine, a California based startup trying to improve the world through collaborative giving. I'm the first engineer they hired to work on the platform.
user_title: Software Engineer
email: mauriurraco@gmail.com
# twitter_username: lorem_ipsum
instagram_username: mauriciourraco7
facebook_username: mauricio.urraco
linkedin_username: murraco
github_username:  murraco
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum
##
public_dev: https://dev.whiteravens.net/?controller=BoardViewController&action=readonly&token=d9ab6bf9453f039493a22fa541024695ed1b9061274eeadb0bc96e70533f

exclude: ['package.json', 'src', 'node_modules', 'vendor']

