# Site settings
title: White Ravens Home
description: Baza główna White Ravens
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://whiteravens.net" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: White Ravens Home
user_description: Witaj na stronie głównej WR. Tworzymy społeczność graczy oraz usługi sieciowe. Wierzymy w ideę wolnego oprogramowania i zdecentralizowanego internetu, który szanuje prywatność użytkowników. Dołącz do Nas i poznaj Naszą społeczność. 
user_title: White Ravens 2.0
email: kontakt@whiteravens.net
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
# facebook_username: whiteravensnet
mastodon_username: whiteravens
# linkedin_username: murraco
steam_group_username: whiteravensgaming
github_username:  whiteravens20
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum
##
public_dev: https://github.com/orgs/whiteravens20/projects/8

exclude: ['package.json', 'src', 'node_modules', 'vendor']

